import type { Game } from '@/types';

// Auto-generated by scripts/boardgame_source_expander.py.
export const GAME_DATABASE_CATALOG_EXPANSION: Game[] = [
  {
    "id": "architectsofthewestkingdom",
    "titleCn": "西国建筑师",
    "titleEn": "Architects of the West Kingdom",
    "coverUrl": "/game-covers/architectsofthewestkingdom.png",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 31,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "工人放置",
      "烧脑策略",
      "文明历史",
      "商业经营"
    ],
    "oneLiner": "一款适合2-5人、约31分钟的文明历史主题的工人放置桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Architects%20of%20the%20West%20Kingdom%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV14r4y197Ks",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "236457",
    "bggUrl": "https://boardgamegeek.com/boardgame/236457",
    "knowledgeTier": "catalog"
  },
  {
    "id": "canvas",
    "titleCn": "画布",
    "titleEn": "Canvas",
    "coverUrl": "/game-covers/canvas.png",
    "minPlayers": 1,
    "maxPlayers": 5,
    "playtimeMin": 19,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "家庭同乐",
      "手牌管理",
      "轻松休闲",
      "收集组合"
    ],
    "oneLiner": "一款适合1-5人、约19分钟的手牌管理桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Canvas%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV14e411s7rN",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "290236",
    "bggUrl": "https://boardgamegeek.com/boardgame/290236",
    "knowledgeTier": "catalog"
  },
  {
    "id": "forbiddenisland",
    "titleCn": "禁闭岛",
    "titleEn": "Forbidden Island",
    "coverUrl": "/game-covers/forbiddenisland.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 24,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "合作共赢",
      "手牌管理",
      "低冲突友好",
      "收集组合"
    ],
    "oneLiner": "一款适合2-4人、约24分钟的手牌管理桌游，上手后通常很容易形成自己的偏好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Forbidden%20Island%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1KW411Q74p",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "65244",
    "bggUrl": "https://boardgamegeek.com/boardgame/65244",
    "knowledgeTier": "catalog"
  },
  {
    "id": "hadrianswall",
    "titleCn": "哈德良长城",
    "titleEn": "Hadrian's Wall",
    "coverUrl": "/game-covers/hadrianswall.png",
    "minPlayers": 1,
    "maxPlayers": 6,
    "playtimeMin": 22,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "朋友聚会",
      "手牌管理",
      "烧脑策略",
      "文明历史"
    ],
    "oneLiner": "一款适合1-6人、约22分钟的文明历史主题的手牌管理桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Hadrian%27s%20Wall%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Ly4y1W7Wm",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "304783",
    "bggUrl": "https://boardgamegeek.com/boardgame/304783",
    "knowledgeTier": "catalog"
  },
  {
    "id": "lorenzo",
    "titleCn": "辉煌的洛伦佐",
    "titleEn": "Lorenzo il Magnifico",
    "coverUrl": "/game-covers/lorenzo.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 42,
    "ageRating": 14,
    "complexity": 4.0,
    "tags": [
      "工人放置",
      "烧脑策略",
      "文明历史"
    ],
    "oneLiner": "一款适合2-4人、约42分钟的文明历史主题的工人放置桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Lorenzo%20il%20Magnifico%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV16V411C77n",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "203993",
    "bggUrl": "https://boardgamegeek.com/boardgame/203993",
    "knowledgeTier": "catalog"
  },
  {
    "id": "russianrailroads",
    "titleCn": "俄罗斯铁路",
    "titleEn": "Russian Railroads",
    "coverUrl": "/game-covers/russianrailroads.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 42,
    "ageRating": 14,
    "complexity": 4.0,
    "tags": [
      "路线规划",
      "烧脑策略",
      "工人放置"
    ],
    "oneLiner": "一款适合2-4人、约42分钟的路线规划桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Russian%20Railroads%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1264y1Y7sS",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "144733",
    "bggUrl": "https://boardgamegeek.com/boardgame/144733",
    "knowledgeTier": "catalog"
  },
  {
    "id": "saintpetersburg",
    "titleCn": "圣彼得堡",
    "titleEn": "Saint Petersburg",
    "coverUrl": "/game-covers/saintpetersburg.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 13,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "手牌管理",
      "文明历史",
      "收集组合"
    ],
    "oneLiner": "一款适合2-4人、约13分钟的文明历史主题的手牌管理桌游，上手后通常很容易形成自己的偏好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Saint%20Petersburg%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1vq4y1n7JR",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "9217",
    "bggUrl": "https://boardgamegeek.com/boardgame/9217",
    "knowledgeTier": "catalog"
  },
  {
    "id": "sushigoparty",
    "titleCn": "寿司派对",
    "titleEn": "Sushi Go Party!",
    "coverUrl": "/game-covers/sushigoparty.png",
    "minPlayers": 2,
    "maxPlayers": 8,
    "playtimeMin": 20,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "家庭同乐",
      "手牌管理",
      "轻松休闲",
      "收集组合"
    ],
    "oneLiner": "一款适合2-8人、约20分钟的手牌管理桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Sushi%20Go%20Party%21%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1LW411t7Jp",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "192291",
    "bggUrl": "https://boardgamegeek.com/boardgame/192291",
    "knowledgeTier": "catalog"
  },
  {
    "id": "teotihuacan",
    "titleCn": "特奥蒂瓦坎：众神之城",
    "titleEn": "Teotihuacan: City of Gods",
    "coverUrl": "/game-covers/teotihuacan.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 41,
    "ageRating": 14,
    "complexity": 3.0,
    "tags": [
      "工人放置",
      "烧脑策略",
      "文明历史",
      "拼图布局"
    ],
    "oneLiner": "一款适合2-4人、约41分钟的文明历史主题的工人放置桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Teotihuacan%3A%20City%20of%20Gods%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV12y4y1L7pn",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "229853",
    "bggUrl": "https://boardgamegeek.com/boardgame/229853",
    "knowledgeTier": "catalog"
  },
  {
    "id": "trio",
    "titleCn": "回忆三重奏",
    "titleEn": "Trio",
    "coverUrl": "/game-covers/trio.png",
    "minPlayers": 3,
    "maxPlayers": 6,
    "playtimeMin": 20,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "朋友聚会",
      "手牌管理",
      "轻松休闲",
      "收集组合"
    ],
    "oneLiner": "一款适合3-6人、约20分钟的手牌管理桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Trio%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1CT421a7rh",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "352515",
    "bggUrl": "https://boardgamegeek.com/boardgame/352515",
    "knowledgeTier": "catalog"
  },
  {
    "id": "yokohama",
    "titleCn": "横滨",
    "titleEn": "Yokohama",
    "coverUrl": "/game-covers/yokohama.png",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 68,
    "ageRating": 14,
    "complexity": 3.0,
    "tags": [
      "工人放置",
      "烧脑策略",
      "文明历史",
      "收集组合"
    ],
    "oneLiner": "一款适合2-4人、约68分钟的文明历史主题的工人放置桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Yokohama%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1U24y177Mu",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "196340",
    "bggUrl": "https://boardgamegeek.com/boardgame/196340",
    "knowledgeTier": "catalog"
  }
];
