import type { Game } from '@/types';

// Auto-generated by scripts/boardgame_source_expander.py.
export const GAME_DATABASE_AUTO_EXPANSION: Game[] = [
  {
    "id": "sevenwondersarchitects",
    "titleCn": "七大奇迹建筑师",
    "titleEn": "7 Wonders Architects",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/sevenwondersarchitects/box/en_280.png?h=1651658788",
    "minPlayers": 2,
    "maxPlayers": 7,
    "playtimeMin": 20,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "朋友聚会",
      "手牌管理",
      "轻松休闲",
      "文明历史"
    ],
    "oneLiner": "一款适合2-7人、约20分钟的文明历史主题的手牌管理桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=7%20Wonders%20Architects%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1HF411F7Zs",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "346703",
    "bggUrl": "https://boardgamegeek.com/boardgame/346703",
    "knowledgeTier": "catalog"
  },
  {
    "id": "cantstop",
    "titleCn": "别停",
    "titleEn": "Can't Stop",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/cantstop/box/en_280.png?h=1651658243",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 20,
    "ageRating": 8,
    "complexity": 1.5,
    "tags": [
      "家庭同乐",
      "安静对弈",
      "骰子驱动",
      "轻松休闲"
    ],
    "oneLiner": "一款适合2-4人、约20分钟的骰子驱动桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Can%27t%20Stop%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1UT4y127Wu",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "41",
    "bggUrl": "https://boardgamegeek.com/boardgame/41",
    "knowledgeTier": "catalog"
  },
  {
    "id": "captainflip",
    "titleCn": "扬翻夺宝",
    "titleEn": "Captain Flip",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/captainflip/box/en_280.png?h=1697386992",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 20,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "朋友聚会",
      "收集组合",
      "轻松休闲",
      "家庭同乐"
    ],
    "oneLiner": "一款适合2-5人、约20分钟的收集组合桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Captain%20Flip%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1DJ4m1T79Y",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "393325",
    "bggUrl": "https://boardgamegeek.com/boardgame/393325",
    "knowledgeTier": "catalog"
  },
  {
    "id": "cartographers",
    "titleCn": "王国制图师",
    "titleEn": "Cartographers",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/cartographers/box/en_280.png?h=1733298773",
    "minPlayers": 1,
    "maxPlayers": 12,
    "playtimeMin": 12,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "朋友聚会",
      "纸笔规划",
      "低冲突友好",
      "拼图布局"
    ],
    "oneLiner": "一款适合1-12人、约12分钟的纸笔规划桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Cartographers%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV18v4y1o7WC",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "263918",
    "bggUrl": "https://boardgamegeek.com/boardgame/263918",
    "knowledgeTier": "catalog"
  },
  {
    "id": "castlecombo",
    "titleCn": "城堡嘉年华",
    "titleEn": "Castle Combo",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/castlecombo/box/en_280.png?h=1715323317",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 20,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "家庭同乐",
      "收集组合",
      "轻松休闲",
      "拼图布局"
    ],
    "oneLiner": "一款适合2-5人、约20分钟的收集组合桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Castle%20Combo%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1V17czpEPH",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "416851",
    "bggUrl": "https://boardgamegeek.com/boardgame/416851",
    "knowledgeTier": "catalog"
  },
  {
    "id": "caverna",
    "titleCn": "洞穴农夫",
    "titleEn": "Caverna",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/caverna/box/en_280.png?h=1663882478",
    "minPlayers": 1,
    "maxPlayers": 7,
    "playtimeMin": 61,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "团建破冰",
      "工人放置",
      "烧脑策略",
      "文明历史"
    ],
    "oneLiner": "一款适合1-7人、约61分钟的文明历史主题的工人放置桌游，很适合拿来破冰暖场。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Caverna%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1E14y1a7jD",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "102794",
    "bggUrl": "https://boardgamegeek.com/boardgame/102794",
    "knowledgeTier": "catalog"
  },
  {
    "id": "chakra",
    "titleCn": "脉轮",
    "titleEn": "Chakra",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/chakra/box/en_280.png?h=1651658270",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 20,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "家庭同乐",
      "安静对弈",
      "抽象对战",
      "轻松休闲"
    ],
    "oneLiner": "一款适合2-4人、约20分钟的抽象对战桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Chakra%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Df4y1g71A",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "267378",
    "bggUrl": "https://boardgamegeek.com/boardgame/267378",
    "knowledgeTier": "catalog"
  },
  {
    "id": "clansofcaledonia",
    "titleCn": "卡利多尼亚氏族",
    "titleEn": "Clans of Caledonia",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/clansofcaledonia/box/en_280.png?h=1651658290",
    "minPlayers": 1,
    "maxPlayers": 4,
    "playtimeMin": 30,
    "ageRating": 14,
    "complexity": 4.0,
    "tags": [
      "引擎构筑",
      "烧脑策略",
      "商业经营",
      "文明历史"
    ],
    "oneLiner": "一款适合1-4人、约30分钟的商业经营主题的引擎构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Clans%20of%20Caledonia%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1WcHLzWEDE",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "216132",
    "bggUrl": "https://boardgamegeek.com/boardgame/216132",
    "knowledgeTier": "catalog"
  },
  {
    "id": "cubirds",
    "titleCn": "方鸟",
    "titleEn": "CuBirds",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/cubirds/box/en_280.png?h=1651658325",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 20,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "家庭同乐",
      "手牌管理",
      "轻松休闲",
      "自然动物"
    ],
    "oneLiner": "一款适合2-5人、约20分钟的自然动物主题的手牌管理桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=CuBirds%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Ha4y177t6",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "245476",
    "bggUrl": "https://boardgamegeek.com/boardgame/245476",
    "knowledgeTier": "catalog"
  },
  {
    "id": "faraway",
    "titleCn": "遥远之地",
    "titleEn": "Faraway",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/faraway/box/en_280.png?h=1691269203",
    "minPlayers": 2,
    "maxPlayers": 7,
    "playtimeMin": 20,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "朋友聚会",
      "收集组合",
      "团建破冰"
    ],
    "oneLiner": "一款适合2-7人、约20分钟的收集组合桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Faraway%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Dq6bYrE3J",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "385761",
    "bggUrl": "https://boardgamegeek.com/boardgame/385761",
    "knowledgeTier": "catalog"
  },
  {
    "id": "flipseven",
    "titleCn": "翻转7",
    "titleEn": "Flip 7",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/flipseven/box/en_280.png?h=1734951722",
    "minPlayers": 3,
    "maxPlayers": 12,
    "playtimeMin": 10,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "朋友聚会",
      "手牌管理",
      "欢乐搞笑",
      "轻松休闲"
    ],
    "oneLiner": "一款适合3-12人、约10分钟的手牌管理桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Flip%207%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1WiP5eJEbB",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "420087",
    "bggUrl": "https://boardgamegeek.com/boardgame/420087",
    "knowledgeTier": "catalog"
  },
  {
    "id": "gaiaproject",
    "titleCn": "盖亚计划",
    "titleEn": "Gaia Project",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/gaiaproject/box/en_280.png?h=1651658421",
    "minPlayers": 1,
    "maxPlayers": 4,
    "playtimeMin": 57,
    "ageRating": 14,
    "complexity": 4.0,
    "tags": [
      "引擎构筑",
      "烧脑策略",
      "科幻太空",
      "低冲突友好"
    ],
    "oneLiner": "一款适合1-4人、约57分钟的科幻太空主题的引擎构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Gaia%20Project%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1pB4y1M7Sm",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "220308",
    "bggUrl": "https://boardgamegeek.com/boardgame/220308",
    "knowledgeTier": "catalog"
  },
  {
    "id": "gizmos",
    "titleCn": "小小发明",
    "titleEn": "Gizmos",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/gizmos/box/en_280.png?h=1665493171",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 13,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "安静对弈",
      "引擎构筑",
      "低冲突友好",
      "收集组合"
    ],
    "oneLiner": "一款适合2-4人、约13分钟的引擎构筑桌游，上手后通常很容易形成自己的偏好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Gizmos%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV19E411Y7bY",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "246192",
    "bggUrl": "https://boardgamegeek.com/boardgame/246192",
    "knowledgeTier": "catalog"
  },
  {
    "id": "greatwesterntrail",
    "titleCn": "大西部之路",
    "titleEn": "Great Western Trail",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/greatwesterntrail/box/en_280.png?h=1651658447",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 56,
    "ageRating": 14,
    "complexity": 3.0,
    "tags": [
      "手牌管理",
      "烧脑策略",
      "文明历史",
      "路线规划"
    ],
    "oneLiner": "一款适合2-4人、约56分钟的文明历史主题的手牌管理桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Great%20Western%20Trail%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1mx411j76k",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "341169",
    "bggUrl": "https://boardgamegeek.com/boardgame/341169",
    "knowledgeTier": "catalog"
  },
  {
    "id": "itsawonderfulworld",
    "titleCn": "美丽新世界",
    "titleEn": "It's a Wonderful World",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/itsawonderfulworld/box/en_280.png?h=1653380555",
    "minPlayers": 1,
    "maxPlayers": 5,
    "playtimeMin": 14,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "引擎构筑",
      "烧脑策略",
      "科幻太空",
      "收集组合"
    ],
    "oneLiner": "一款适合1-5人、约14分钟的科幻太空主题的引擎构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=It%27s%20a%20Wonderful%20World%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Tg411m7FB",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "271324",
    "bggUrl": "https://boardgamegeek.com/boardgame/271324",
    "knowledgeTier": "catalog"
  },
  {
    "id": "lostcities",
    "titleCn": "失落的城市",
    "titleEn": "Lost Cities",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/lostcities/box/en_280.png?h=1651658579",
    "minPlayers": 2,
    "maxPlayers": 2,
    "playtimeMin": 20,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "情侣约会",
      "高互动对抗",
      "手牌管理",
      "轻松休闲"
    ],
    "oneLiner": "一款适合2人、约20分钟的手牌管理桌游，双人对玩也不会太有压力。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Lost%20Cities%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV197411N7nn",
    "bestPlayerCount": [
      2
    ],
    "bggId": "50",
    "bggUrl": "https://boardgamegeek.com/boardgame/50",
    "knowledgeTier": "catalog"
  },
  {
    "id": "arnak",
    "titleCn": "失落的阿纳克遗迹",
    "titleEn": "Lost Ruins of Arnak",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/arnak/box/en_280.png?h=1651658175",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 29,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "卡组构筑",
      "烧脑策略",
      "工人放置",
      "竞速赛跑"
    ],
    "oneLiner": "一款适合2-4人、约29分钟的卡组构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Lost%20Ruins%20of%20Arnak%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1JG411t7h8",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "312484",
    "bggUrl": "https://boardgamegeek.com/boardgame/312484",
    "knowledgeTier": "catalog"
  },
  {
    "id": "luckynumbers",
    "titleCn": "幸运数字",
    "titleEn": "Lucky Numbers",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/luckynumbers/box/en_280.png?h=1651658587",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 20,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "安静对弈",
      "抽象对战",
      "轻松休闲",
      "拼图布局"
    ],
    "oneLiner": "一款适合2-4人、约20分钟的抽象对战桌游，上手后通常很容易形成自己的偏好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Lucky%20Numbers%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1qU4y1374U",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "118247",
    "bggUrl": "https://boardgamegeek.com/boardgame/118247",
    "knowledgeTier": "catalog"
  },
  {
    "id": "photosynthesis",
    "titleCn": "光合作用",
    "titleEn": "Photosynthesis",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/photosynthesis/box/en_280.png?h=1664776940",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 32,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "家庭同乐",
      "安静对弈",
      "抽象对战",
      "低冲突友好"
    ],
    "oneLiner": "一款适合2-4人、约32分钟的抽象对战桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Photosynthesis%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Ts411w7sJ",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "218603",
    "bggUrl": "https://boardgamegeek.com/boardgame/218603",
    "knowledgeTier": "catalog"
  },
  {
    "id": "raceforthegalaxy",
    "titleCn": "银河竞逐",
    "titleEn": "Race for the Galaxy",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/raceforthegalaxy/box/en_280.png?h=1651658726",
    "minPlayers": 2,
    "maxPlayers": 6,
    "playtimeMin": 60,
    "ageRating": 14,
    "complexity": 4.0,
    "tags": [
      "引擎构筑",
      "烧脑策略",
      "科幻太空",
      "手牌管理"
    ],
    "oneLiner": "一款适合2-6人、约60分钟的科幻太空主题的引擎构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Race%20for%20the%20Galaxy%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1fJ411h7St",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "28143",
    "bggUrl": "https://boardgamegeek.com/boardgame/28143",
    "knowledgeTier": "catalog"
  },
  {
    "id": "railroadink",
    "titleCn": "铁道墨水",
    "titleEn": "Railroad Ink",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/railroadink/box/en_280.png?h=1651658730",
    "minPlayers": 1,
    "maxPlayers": 12,
    "playtimeMin": 20,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "朋友聚会",
      "纸笔规划",
      "低冲突友好",
      "路线规划"
    ],
    "oneLiner": "一款适合1-12人、约20分钟的纸笔规划桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Railroad%20Ink%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Mt41117Ak",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "245654",
    "bggUrl": "https://boardgamegeek.com/boardgame/245654",
    "knowledgeTier": "catalog"
  },
  {
    "id": "regicide",
    "titleCn": "弑君者",
    "titleEn": "Regicide",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/regicide/box/en_280.png?h=1655575401",
    "minPlayers": 1,
    "maxPlayers": 4,
    "playtimeMin": 12,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "合作共赢",
      "手牌管理",
      "低冲突友好",
      "收集组合"
    ],
    "oneLiner": "一款适合1-4人、约12分钟的手牌管理桌游，上手后通常很容易形成自己的偏好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Regicide%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Ei4y1R7XE",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "307002",
    "bggUrl": "https://boardgamegeek.com/boardgame/307002",
    "knowledgeTier": "catalog"
  },
  {
    "id": "resarcana",
    "titleCn": "奥法对决",
    "titleEn": "Res Arcana",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/resarcana/box/en_280.png?h=1651658738",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 22,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "高互动对抗",
      "引擎构筑",
      "烧脑策略",
      "手牌管理"
    ],
    "oneLiner": "一款适合2-5人、约22分钟的引擎构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Res%20Arcana%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1N2d2YWEgV",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "262712",
    "bggUrl": "https://boardgamegeek.com/boardgame/262712",
    "knowledgeTier": "catalog"
  },
  {
    "id": "seasons",
    "titleCn": "四季物语",
    "titleEn": "Seasons",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/seasons/box/en_280.png?h=1651658774",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 18,
    "ageRating": 14,
    "complexity": 3.0,
    "tags": [
      "引擎构筑",
      "烧脑策略",
      "骰子驱动",
      "手牌管理"
    ],
    "oneLiner": "一款适合2-4人、约18分钟的引擎构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Seasons%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV17U4y1o7uq",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "108745",
    "bggUrl": "https://boardgamegeek.com/boardgame/108745",
    "knowledgeTier": "catalog"
  },
  {
    "id": "stoneage",
    "titleCn": "石器时代",
    "titleEn": "Stone Age",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/stoneage/box/en_280.png?h=1651658845",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 21,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "工人放置",
      "烧脑策略",
      "文明历史",
      "骰子驱动"
    ],
    "oneLiner": "一款适合2-5人、约21分钟的文明历史主题的工人放置桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Stone%20Age%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1kt411P7Px",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "34635",
    "bggUrl": "https://boardgamegeek.com/boardgame/34635",
    "knowledgeTier": "catalog"
  },
  {
    "id": "supermegaluckybox",
    "titleCn": "超级幸运盒",
    "titleEn": "Super Mega Lucky Box",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/supermegaluckybox/box/en_280.png?h=1651651817",
    "minPlayers": 1,
    "maxPlayers": 12,
    "playtimeMin": 20,
    "ageRating": 8,
    "complexity": 1.0,
    "tags": [
      "家庭同乐",
      "安静对弈",
      "纸笔规划",
      "轻松休闲"
    ],
    "oneLiner": "一款适合1-12人、约20分钟的纸笔规划桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Super%20Mega%20Lucky%20Box%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1kQVvewERQ",
    "bestPlayerCount": [
      5,
      6
    ],
    "bggId": "341530",
    "bggUrl": "https://boardgamegeek.com/boardgame/341530",
    "knowledgeTier": "catalog"
  },
  {
    "id": "thecrew",
    "titleCn": "星际探险队",
    "titleEn": "The Crew",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/thecrew/box/en_280.png?h=1651658884",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 31,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "合作共赢",
      "吃墩叫牌",
      "低冲突友好",
      "科幻太空"
    ],
    "oneLiner": "一款适合2-5人、约31分钟的科幻太空主题的吃墩叫牌桌游，上手后通常很容易形成自己的偏好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=The%20Crew%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1HP4y1n7yb",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "284083",
    "bggUrl": "https://boardgamegeek.com/boardgame/284083",
    "knowledgeTier": "catalog"
  },
  {
    "id": "isleofcats",
    "titleCn": "猫岛奇缘",
    "titleEn": "The Isle of Cats",
    "coverUrl": "",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 30,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "家庭同乐",
      "拼图布局",
      "低冲突友好",
      "收集组合"
    ],
    "oneLiner": "一款适合2-4人、约30分钟的拼图布局桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Isleofcats%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1S34y1y7jf",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "",
    "bggUrl": "",
    "knowledgeTier": "catalog"
  },
  {
    "id": "throughtheages",
    "titleCn": "历史巨轮",
    "titleEn": "Through the Ages",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/throughtheages/box/en_280.png?h=1651658901",
    "minPlayers": 2,
    "maxPlayers": 4,
    "playtimeMin": 100,
    "ageRating": 14,
    "complexity": 5.0,
    "tags": [
      "引擎构筑",
      "烧脑策略",
      "文明历史",
      "手牌管理"
    ],
    "oneLiner": "一款适合2-4人、约100分钟的文明历史主题的引擎构筑桌游，更适合想认真动脑的玩家。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Through%20the%20Ages%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1Sx411n7aQ",
    "bestPlayerCount": [
      3,
      4
    ],
    "bggId": "25613",
    "bggUrl": "https://boardgamegeek.com/boardgame/25613",
    "knowledgeTier": "catalog"
  },
  {
    "id": "tipperary",
    "titleCn": "Tipperary",
    "titleEn": "Tipperary",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/tipperary/box/en_280.png?h=1767948937",
    "minPlayers": 2,
    "maxPlayers": 5,
    "playtimeMin": 12,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "家庭同乐",
      "拼图布局",
      "轻松休闲",
      "低冲突友好"
    ],
    "oneLiner": "一款适合2-5人、约12分钟的拼图布局桌游，带新手或家人上桌都比较友好。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Tipperary%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1SfXxBpEVD",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "378983",
    "bggUrl": "https://boardgamegeek.com/boardgame/378983",
    "knowledgeTier": "catalog"
  },
  {
    "id": "toybattle",
    "titleCn": "玩具大作战",
    "titleEn": "Toy Battle",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/toybattle/box/en_280.png?h=1744884466",
    "minPlayers": 2,
    "maxPlayers": 2,
    "playtimeMin": 20,
    "ageRating": 10,
    "complexity": 2.0,
    "tags": [
      "情侣约会",
      "安静对弈",
      "拼图布局"
    ],
    "oneLiner": "一款适合2人、约20分钟的拼图布局桌游，双人对玩也不会太有压力。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Toy%20Battle%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1GdWdzdEsh",
    "bestPlayerCount": [
      2
    ],
    "bggId": "434654",
    "bggUrl": "https://boardgamegeek.com/boardgame/434654",
    "knowledgeTier": "catalog"
  },
  {
    "id": "viticulture",
    "titleCn": "葡萄酒庄园",
    "titleEn": "Viticulture",
    "coverUrl": "https://x.boardgamearena.net/data/gamemedia/viticulture/box/en_280.png?h=1651658965",
    "minPlayers": 1,
    "maxPlayers": 6,
    "playtimeMin": 43,
    "ageRating": 12,
    "complexity": 3.0,
    "tags": [
      "朋友聚会",
      "工人放置",
      "烧脑策略",
      "商业经营"
    ],
    "oneLiner": "一款适合1-6人、约43分钟的商业经营主题的工人放置桌游，拿来朋友聚会通常很稳。",
    "rules": {
      "target": "",
      "flow": "",
      "tips": ""
    },
    "FAQ": "",
    "commonQuestions": [],
    "knowledgeBase": "",
    "tutorialVideoUrl": "https://search.bilibili.com/all?keyword=Viticulture%20%E6%A1%8C%E6%B8%B8%E6%95%99%E5%AD%A6",
    "bilibiliId": "BV1rs411v7GR",
    "bestPlayerCount": [
      4,
      5
    ],
    "bggId": "128621",
    "bggUrl": "https://boardgamegeek.com/boardgame/128621",
    "knowledgeTier": "catalog"
  }
];
